### ISSUE TITLE
Metadata in configuration (for filtering)

### ISSUE THREAD

**Issue by chicoreus** [kurator-org/kurator-web#11]
From the roadmap: Define metadata in the workflows.conf file describing workflow input and output types (CSV, DwCA). Also add support for listing the set of information elements that the workflow is relevant to.

**Comment by lowery** [comment]
See https://github.com/kurator-org/kurator-validation/commit/62a25c61d11d977a681e1430c82ff771a1d482ed for changes to config with additional metadata.

Still need to modify the configuration parser in the web app to support the new format.

**Comment by lowery** [comment]
See c3af8dd, 9a7c7ff and b95455d for configuration parsing support in the web app.
