### ISSUE TITLE
Allow users to filter/find workflows they want

### ISSUE THREAD

**Issue by chicoreus** [kurator-org/kurator-web#12]
From the roadmap: "Filtering workflows list view - Add ability to search workflows by input and output file types or enter a list of terms to filter by information element (e.g. find all workflows that act on dwc:decimalLatitude and dwc:decimalLongitude)"  http://wiki.datakurator.org/wiki/Roadmap#Kurator-Web:_Workflows_page_UI

**Comment by chicoreus** [comment]
Depends on #11

**Comment by lowery** [comment]
See b95455d, 32ab0ab, b6cfae3 for updates to the list of workflows and the forms in the UI and backend.

Similar workflows in the list have been consolidated and now display multiple "Run With" buttons for each of the supported input types (CSV File, DwCA URL).

**Comment by lowery** [comment]
Filtering feature implemented and deployed.
