### ISSUE TITLE
FFDQ spreadsheet representation has status:complete for a numeric measure

### ISSUE THREAD

**Issue by chicoreus** [kurator-org/kurator-web#22]
Spreadsheet rendering of FFDQ results asserts status =complete for measures with a numeric result. 

Measures | Status |  Value
MEASURE_EVENT_RANGEINSECONDS | COMPLETE | 86399

Should probably add a status=MEASURED for measures with numeric results.

**Comment by lowery** [comment]
See: https://github.com/kurator-org/kurator-ffdq/commit/ad3794f95fe249ce9914ec1e94c7e30b34bdd53e
