### ISSUE TITLE
FFDQ Spreadsheet doesn't show amended values.

### ISSUE THREAD

**Issue by chicoreus** [kurator-org/kurator-web#23]
An FFDQ spreadsheet result showing an amendment result with the comment: "Added day [12] from eventDate [1974-02-12].\|Added month [2] from eventDate [1974-02-12].\|Added month [2] from eventDate [1974-02-12].\|Added year [1974] from eventDate [1974-02-12].\|Added startDayOfYear [43] from eventDate [1974-02-12].\|Added endDayOfYear [43] from eventDate [1974-02-12]."   

does not contain values in day, month, year, etc, in either the Amendments sheet or the final values sheet.  The relevant cells have colored highlighting, but do not contain the text of the amended values.

**Comment by lowery** [comment]
see: https://github.com/kurator-org/kurator-ffdq/commit/ad3794f95fe249ce9914ec1e94c7e30b34bdd53e
