### ISSUE TITLE
Workflows Names

### ISSUE THREAD

**Issue by pzermoglio** [kurator-org/kurator-web#3]
The names of some workflows listed contain "CSV...." (e.g., "CSV File Aggregator"). If I understand correctly, this does not mean that the only input format is indeed .csv . The names then seem a bit misleading. Could they be changed to not include "CSV" in them?

**Comment by lowery** [comment]
I've consolidated the workflows in c3bfed4 and they will look something like the example screenshot below in the next deployment of updates. Is this close to what you had in mind?

![screenshot from 2018-02-28 14-32-53](https://user-images.githubusercontent.com/1214314/36809068-e14bbbb8-1c94-11e8-8a84-40ea237b8b3b.png)

**Comment by lowery** [comment]
Added as part of #12 for filtering
