### ISSUE TITLE
Accessing Kurator workflows from the webpage

### ISSUE THREAD

**Issue by pzermoglio** [kurator-org/kurator-web#4]
If one is not registered and logged in yet, it is very difficult to understand how to access the workflows from the webpage (http://kurator.acis.ufl.edu/kurator-web/), as the "Workflows" tab is not visible. It took me a while to figure out I had to register to access the tool. It may be helpful to have a brief text in the page saying something like "To see the workflows log in or register here".

**Comment by lowery** [comment]
I added the text "Login or Register a user account to access the web application and run the workflows or see the About page for more info." to the home page. 

Will be up on kurator.acis.ufl.edu after the next deployment of updates.

**Comment by lowery** [comment]
Added the text to the homepage of kurator-web
