### ISSUE TITLE
Logging off when a Workflow started

### ISSUE THREAD

**Issue by bradmROM** [kurator-org/kurator-web#9]
Hi:

I am reading the wiki at http://wiki.datakurator.org/wiki/Kurator-Web_User_Documentation

No where in the above is there a mention about being able to log off of Kurator after a Workflow is initialised.

I would assume so but...... my browser is still open.

Brad MIllen

**Comment by lowery** [comment]
Hi,

Yes, you can safely log off or close the browser window and the workflow will continue running in the background. I've just added some text to the wiki documenting this here: http://wiki.datakurator.org/wiki/Kurator-Web_User_Documentation#Running_a_Workflow
